"""
Streamlit gallery app for PNGs generated by SVG word generation pipeline

pip install streamlit==1.47.0

streamlit run src/svg_word_generation/svg_gen_img_visualizer.py --server.port 8443

Forward port 8443 to your local machine and open http://localhost:8443 in your browser
ssh -L 8443:localhost:8443 107614.od.fbinfra.net
"""

import json
from pathlib import Path
from typing import List

import streamlit as st
from PIL import Image

# ------------------------------
# Configuration
# ------------------------------
st.set_page_config(page_title="PNG Gallery", layout="wide")

DEFAULT_DIR = Path("data/processed/svg_word_generation/pangrams/")


# ------------------------------
# Helper functions (cached)
# ------------------------------
@st.cache_resource(show_spinner=False)
def list_pngs(directory: Path) -> List[Path]:
    """Return a sorted list of all .png files in *directory* (non-recursive)."""
    return sorted(directory.glob("*.png"))


@st.cache_resource(show_spinner=False)
def load_image(path: Path) -> Image.Image:
    """Open an image from *path* and cache the result."""
    return Image.open(path)


def resize_image_to_height(image: Image.Image, target_height: int) -> Image.Image:
    """Resize image to target height while maintaining aspect ratio."""
    aspect_ratio = image.width / image.height
    target_width = int(target_height * aspect_ratio)
    return image.resize((target_width, target_height), Image.Resampling.LANCZOS)


# ------------------------------
# Sidebar controls
# ------------------------------
st.sidebar.header("📁 Source directory")
base_dir = Path(st.sidebar.text_input("SVG word base dir", value=str(DEFAULT_DIR)))
img_dir = base_dir / "png"


if not img_dir.exists():
    st.sidebar.error("Directory does not exist.")
    st.stop()

all_pngs = list_pngs(img_dir)

if not all_pngs:
    st.sidebar.warning("No PNG files found in the selected directory.")
    st.stop()

st.sidebar.header("🔧 Display options")
page_size = st.sidebar.slider("Images per page", 10, 1000, 50, 10)
columns = st.sidebar.slider("Columns", 1, 6, 3)
show_captions = st.sidebar.checkbox("Show captions", value=True)

# Pagination
num_pages = (len(all_pngs) + page_size - 1) // page_size

# Initialize session state for current page if not exists
if "current_page" not in st.session_state:
    st.session_state.current_page = 1

# Direction arrows for page navigation
col1, col2, col3 = st.sidebar.columns([1, 2, 1])

with col1:
    if st.button(
        "◀", help="Previous page", disabled=(st.session_state.current_page <= 1)
    ):
        st.session_state.current_page = max(1, st.session_state.current_page - 1)
        st.rerun()

with col3:
    if st.button(
        "▶", help="Next page", disabled=(st.session_state.current_page >= num_pages)
    ):
        st.session_state.current_page = min(
            num_pages, st.session_state.current_page + 1
        )
        st.rerun()

# Page number input (sync with session state)
current_page = st.sidebar.number_input(
    "Page", 1, num_pages, st.session_state.current_page, 1, key="page_input"
)

# Update session state if page input changes
if current_page != st.session_state.current_page:
    st.session_state.current_page = current_page

start_idx = (current_page - 1) * page_size
end_idx = min(start_idx + page_size, len(all_pngs))

st.sidebar.markdown(
    f"Showing **{start_idx + 1}–{end_idx}** of **{len(all_pngs)}** images"
)

# ------------------------------
# Main display
# ------------------------------
# st.title("🖼️ PNG Gallery (Framed)")

input_metadata_dir = base_dir / "metadata"
input_jsonl_files = list(Path(input_metadata_dir).glob("*.jsonl"))
print(f"number of jsonl files: {len(input_jsonl_files)}")
data_list = []
for input_jsonl in input_jsonl_files:
    print(f"Loading input_jsonl_file: {input_jsonl}")
    with open(input_jsonl, "r") as f:
        for line in f:
            data_list.append(json.loads(line))
# build mapping
hash_to_metadata = {}
for data in data_list:
    hash_to_metadata[data["output_hash"]] = data


# Set a consistent height for all images in pixels
TARGET_HEIGHT = 200

for row_start in range(start_idx, end_idx, columns):
    row_images = all_pngs[row_start : row_start + columns]

    # Display images in columns
    cols = st.columns(len(row_images))
    row_metadata = []

    for col, img_path in zip(cols, row_images):
        with col:
            output_hash = img_path.stem
            metadata = hash_to_metadata[output_hash]
            row_metadata.append(metadata)

            # Load and resize image to consistent height
            original_image = load_image(img_path)
            resized_image = resize_image_to_height(original_image, TARGET_HEIGHT)

            st.image(
                resized_image,
                use_container_width=False,
            )

    # Display captions in table format if enabled
    if show_captions:
        caption_cols = st.columns(len(row_images))
        for col, metadata in zip(caption_cols, row_metadata):
            with col:
                output_hash = metadata["output_hash"]
                text_svg_len = len(metadata["text_svg"])
                font_name = metadata["font_name"]
                font_file_name = metadata["font_file_name"]
                word = metadata["word"]

                # Display caption in a compact table-like format
                st.markdown(
                    f"""
                <div style="font-size: 10px; line-height: 1.2; margin-top: 5px;">
                <strong>Hash:</strong> {output_hash}<br>
                <strong>Font:</strong> {font_name}<br>
                <strong>File:</strong> {font_file_name}<br>
                <strong>SVG Len:</strong> {text_svg_len}<br>
                <strong>Word:</strong> {word}
                </div>
                """,
                    unsafe_allow_html=True,
                )
